//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDetyra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pyetja
    {
        public int PyetjaID { get; set; }
        public string Pyejta { get; set; }
        public string Opcioni1 { get; set; }
        public string Opcioni2 { get; set; }
        public string Opcioni3 { get; set; }
        public string Opcioni4 { get; set; }
        public string PergjigjjaESakte { get; set; }
    }
}
